sudo: required
jdk:
- oraclejdk8
language: java
services:
- mysql
- docker
before_install:
- sudo apt-get update
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn install
branches:
  only:
  - "/^develop.*$/"
  - "/^master.*$/"
  - "/^v.*$/"